### ISSUE TITLE
Handle no users in voice channels

### ISSUE THREAD

**Issue by matta174** [matta174/DropBot#13]
**Describe the bug**
DropBot gets an error when no user is in the voice channel for commands like !callit and !ez. We should handle an error gracefully.

**To Reproduce**
1. Go to a server with DropBot
2. While the voice channels have no users call callit / ez
4. No response is given because we catch an error and don't follow up.

**Expected behavior**
A message explaining that this command only works if people are in the voice channels

**Screenshots**
![image](https://user-images.githubusercontent.com/11731369/150577723-b7bcfe70-4f2b-4f20-ac5e-f1af2809db35.png)
![image](https://user-images.githubusercontent.com/11731369/150577766-2dbfe4d8-d15f-4ae1-84b7-57fa6b893a3f.png)

**Comment by DipayanP007** [comment]
Hey @matta174 can I work on this? Can you assign me this?

**Comment by matta174** [comment]
Sure, I don't see your username in the comments anymore though

**Comment by jchuff** [comment]
I believe this issue has been resolved with #16 .
