### ISSUE TITLE
Weird information appears in logs

### ISSUE THREAD

**Issue by matta174** [matta174/DropBot#19]
![image](https://user-images.githubusercontent.com/11731369/151436824-7190745b-7b15-4321-ad1a-0ee17b0748e5.png)
This weird entry keeps appearing in logs. Figure out what it is and handle it properly.

**Comment by jchuff** [comment]
So I believe this is tied to the **[Application Command Permissions](https://discord.com/developers/docs/change-log#application-command-permissions)** feature.
Support for this was merged into [discord-net:dev](https://github.com/discord-net/Discord.Net) [here](https://github.com/discord-net/Discord.Net/pull/1923#issue-1000670442)
See: Minor changes > Application Commands

So I think the next version of Discord.Net should fix this?

**Comment by matta174** [comment]
Yep I believe that's correct.  I just have to actually deploy the latest...
